services:
  exchange-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: exchange-app
    restart: unless-stopped
    ports:
      - "3022:3000"
    env_file:
      - .env
    environment:
      # App Config
      - NODE_ENV=production
